### PR TITLE
chat: fb-like msg style re-design

### PR DESCRIPTION
**Pull request by E-RELevant**
Change it to look much more fb-like.

From: 
image
to:
image

### CODE REVIEW

**Comment by E-RELevant** [comment]
> [...] so I'd like to know what it looks like on Windows.

It looks fine:
image

I really do think though finding a better solution to fit the timestamp next to text will benefit this message-style a lot.

**Comment by vednoc** [comment]
Here is what it looks like on my end.

image

With your changes:

image

**Comment by E-RELevant** [comment]
Interesting. In both cases on your end, it seems like the timestamp is a bit beneath the text itself.
As about the timestamp on my end: maybe that's a `Right-to-Left` issue?

**Comment by vednoc** [comment]
We can adjust the timestamp. The problem is in adjusting both LTR and RTL layouts in all cases, which is not really an ideal solution IMO.

**Comment by E-RELevant** [comment]
Added @ `v2.7.0`
https://github.com/vednoc/dark-whatsapp/blob/master/changelog.org#270-2020-05-23-sat

**Comment by vednoc** [comment]
@E-RELevant I suppose we could (re)use this PR to port this feature to v3. What do you think?

**Comment by vednoc** [comment]
@E-RELevant I only need to port RTL hacks for `fb-like` tails to v3 and this PR will be ready for merge. It will need a lot more testing once that's implemented, but let me know if you find bugs in the base styles.

**Pull request merged**
